### ISSUE TITLE
usage license

### ISSUE THREAD

**Issue by rvkrishnan30** [rlabduke/reference_data#2]
Hi,
This rota8000 reference data looks good. Can we use this data under CC BY-SA license?

**Comment by chrissciwilliams** [comment]
Our other datasets on Zenodo ([top2018 protein residues](https://doi.org/10.5281/zenodo.4626149), [rna2023 rna residues](https://doi.org/10.5281/zenodo.8103013)) are licensed as CC-by-4.0  Is that an acceptable license for your needs?

**Comment by jsrrlab** [comment]
Yes

Jane & Dave

Richardson Lab
132 Nanaline Duke Bldg.
Duke U Med Ctr 3711
Durham NC 27710, USA
1-919-684-6010; fax 684-8885
***@***.***
________________________________

**Comment by rvkrishnan30** [comment]
Thank you. Could we have the license file added to this repo too, please. That would be very helpful.

**Comment by chrissciwilliams** [comment]
I have added a CC-BY 4.0 license document to the [Top8000_rotamer_pct_contour_grids](https://github.com/rlabduke/reference_data/tree/master/Top8000/Top8000_rotamer_pct_contour_grids) directory and other relevant directories in reference_data.  Enjoy!
